DataQAudit/DataQAudit/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Excel = Microsoft.Office.Interop.Excel;
using System.IO;
using pocReport.Models;
using Excel;
using System.Data;
using OfficeOpenXml;
using System.Data.OleDb;
using System.Web.Script.Serialization;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Data.SqlClient;
using System.Text;
using DataQAudit;
using System.Web.UI;
using DataQAudit.Models;

namespace pocReport.Controllers
{
    public class ClientController : Controller
    {
        swabzEntities entity = new swabzEntities();
        static string encryptCompanyId =null;
       
        // GET: Client
        public PartialViewResult importExcel()
        {
                return PartialView("excelView");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> uploadExcel(IEnumerable<HttpPostedFileBase> files)
        {
           
            asyncUploadExcel obj = new asyncUploadExcel();
         
            foreach (var file in files)
            {
                if (file != null && file.ContentLength > 0)
                {   //  var fileName =Path.GetExtension(file.FileName);
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Excel"), fileName);
                    file.SaveAs(path);
                }
            }

          


            Task<StringBuilder> statuss =  obj.UploadExcelDataAsync(files, encryptCompanyId);

            StringBuilder status = await statuss;
            if (status!=null)
            {
                 TempData["msg"] = "<script>alert('" + status.ToString() + "');</script>";
             //   TempData["msg"] = "<script> $('#alerts').html(" + status + ");openAlerts()</script>";
                 
            }
            
            return RedirectToAction("home");

     }

      
      

        public ActionResult clients(string userId,string password)
        {
            encryptCompanyId = password;
            try
            {
                string decryptCompanyId = encryptDecrypt.Decrypt(password);    
                
            var user = entity.users.Where(a => a.userId.Equals(userId)).FirstOrDefault();
           
            if (ModelState.IsValid && decryptCompanyId.Equals(user.companyId.ToString()))
                return RedirectToAction("home");
                else
                return RedirectToAction("login");
            }
            catch (Exception e)
            {
                return RedirectToAction("login");
            }
            return RedirectToAction("login");
        }


        public ActionResult home()
        {           
                    return View();               
            }


        usersExcel summaryDefectModel = new usersExcel();
        public ActionResult dashboard()
        {
            try
            {
                var v = entity.userWorksapces.Where(a => a.userId.Equals("swan")).FirstOrDefault();
                v.msg = null; v.defectId = null; v.RunDate = null; v.fileName = null; v.alerts = null;
                entity.SaveChanges();
            }
            catch (Exception e) { }

            return RedirectToAction("about");
        }
        
     public ViewResult about()
        {
            /*  usersExcel user = new usersExcel();
                                           List<usersExcel> userList = new List<usersExcel>();
                                           while (reader.Read())
                                           {
                                               for (int row = 0; row <= 30; row++)                                                                                  
                                                   user.stringDay[row] = reader[row].ToString();   
                                            }

                                   for (int row = 0; row <= 30; row++)
                                       user.intDays[row] = Int32.Parse(user.stringDay[row]);

                                   userList.Add(user);  
                                   string jsondata = new JavaScriptSerializer().Serialize(userList);
                                   string NewString = jsondata.TrimEnd(']').TrimStart('[');
                                   string path = Server.MapPath("~/JSON/");
                                   System.IO.File.WriteAllText(path + "output.json", NewString);
                                    */


            return View();
        }
     

        [HttpPost]
        public DefectDetailsData[] LoadData(string api)
        { 
            string[]  rowData =Regex.Split(api, @"\D+");
            int defectId = Int32.Parse(rowData[1]);   
            int recordsTotal = entity.defectDetails.Where(a=>a.DefectId.Equals(defectId)).Count(),i=0;
           
            string queryString = "SELECT * FROM [dbo].[defectDetails]  where DefectId =" + defectId;
            DefectDetailsData[] localDdd = new DefectDetailsData[recordsTotal];

              

            //  return Json(new { localDdd } , JsonRequestBehavior.AllowGet);
            return localDdd;


        }
    }


}

DataQAudit/DataQAudit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @model IEnumerable<DataQAudit.user>

    @if (Session["LoggedUserId"] != null)
    {
        /*  <br /><br />
            <text> Bonjour! @Session["LoggedUserId"].ToString() </text>
               <br />
                 <text> Company @Session["LoggedCompany"].ToString() </text>
                   <br />*/

    }

    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    
</head>
<body>
 
    <div class="container body-content">
        <link href="~/Content/Site.css" rel="stylesheet" />
        <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
        <link href="~/Content/jquery-ui.css" rel="stylesheet" />

        <nav class="navbar navbar-inverse navbar-fixed-top" style="background-color: maroon" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <img src="~/Content/image/SwaBz-Systems-LLC.jpg" class="navbar-nav " style="margin-top: -3%;height: 52px;margin-left:-50%" />
                </div>


                <div class="panel-body" style="width: 58%;margin-left: 67%;margin-top: -5%;height: 100px">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs " style="border-bottom: 1px solid maroon">
                        <li class="dropdown ">
                            <a id="tm1">@Html.ActionLink("Home", "home", "Client")</a>
                            <!--<div class="dropdown-content list-group">
                             @Html.ActionLink("home1", "home1", "Client")
                             <a href="#" class="list-group-item">home 2</a>
                             <a href="#" class="list-group-item">home 3</a>
                         </div>-->
                        </li>
                        <li class="dropdown " >
                            <a >@Html.ActionLink("Dashboard", "dashboard", "Client")</a>
                            <!--  <div class="dropdown-content list-group">
                              <a href="#" class="list-group-item">about 1</a>
                              <a href="#" class="list-group-item">about 2</a>
                              <a href="#" class="list-group-item">about 3</a>
                          </div>-->
                        </li>
                        <li class="dropdown">
                            <a>    @Html.ActionLink("Logout", "login", "Home")</a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane fade in " id="home">
                        </div>
                        <div class="tab-pane fade" id="profile">
                        </div>
                        <div class="tab-pane fade" id="messages">
                        </div>
                        <div class="tab-pane fade" id="settings">

                        </div>
                    </div>
                </div>





            </div>
        </nav> 
 
    </div>
   
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)

 
</body>
@RenderBody()
</html>